#!/bin/sh
read ipstr
if [ -z "$ipstr" ]
  then
    echo "No input string supplied"
exit
fi

if [ -z "$@" ]
  then
    echo "No argument supplied for password length"
exit
fi
genpass=`(echo "$ipstr" | shuf | base64 -w 0 |  tr '[0-9]' '[a-zA-Z]'  | cut -b 2- | fold -w"$@" | head -n1 | rev | sed 's/./&\n/g' | shuf | tr -d "\n")`
echo $genpass
